<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mony_Loop.Application\Mony_Loop.Application.csproj" />
    <ProjectReference Include="..\Mony_Loop.Infrastructure\Mony_Loop.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Files\Images\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
