// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonyLoop.Infrastructure.Data;

#nullable disable

namespace MonyLoop.Infrastructure.Data.MigrationsV2
{
    [DbContext(typeof(MonyLoopDbContext))]
    [Migration("20260823140419_Module1AccountSecurityAndProfiles")]
    partial class Module1AccountSecurityAndProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Agreement___Payment.MembershipAgreement", b =>
                {
                    b.Property<Guid>("MembershipAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CircleTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContributionSchedule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("MembershipApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PayoutSlot")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("MembershipAgreementId");

                    b.HasIndex("MembershipApplicationId")
                        .IsUnique();

                    b.ToTable("MembershipAgreements", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Agreement___Payment.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberLedgerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("CircleId");

                    b.HasIndex("MemberLedgerId");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", b =>
                {
                    b.Property<Guid>("CircleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovedSlots")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("FilledCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Open");

                    b.HasKey("CircleId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.CircleRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CircleTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CircleType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NewCircle");

                    b.Property<decimal>("ContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByOrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid?>("ExistingCircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfSlots")
                        .HasColumnType("int");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortJustification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VacantSlotNumber")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("CreatedByOrganizerId");

                    b.HasIndex("ExistingCircleId");

                    b.HasIndex("RequestStatus");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("CircleRequests", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.CircleSlot", b =>
                {
                    b.Property<Guid>("CircleSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberLedgerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Vacant");

                    b.Property<DateTime?>("VacatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CircleSlotId");

                    b.HasIndex("MemberLedgerId")
                        .IsUnique()
                        .HasFilter("[MemberLedgerId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("CircleId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("CircleSlots", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.MarketplaceListing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("ListingId");

                    b.HasIndex("CircleId")
                        .IsUnique();

                    b.HasIndex("ListingStatus");

                    b.ToTable("MarketplaceListings", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Marketplace___Applications.MembershipApplication", b =>
                {
                    b.Property<Guid>("MembershipApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Submitted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MembershipApplicationId");

                    b.HasIndex("ListingId");

                    b.HasIndex("Stage");

                    b.HasIndex("UserId");

                    b.ToTable("MembershipApplications", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OnboardingCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentRequirementId");

                    b.HasIndex("OnboardingCaseId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.DocumentRequirement", b =>
                {
                    b.Property<Guid>("DocumentRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DocumentRequirementId");

                    b.ToTable("DocumentRequirements");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.MemberLedger", b =>
                {
                    b.Property<Guid>("MemberLedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ActivatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OnboardingCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberLedgerId");

                    b.HasIndex("ActivatedByAdminId");

                    b.HasIndex("OnboardingCaseId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MemberLedgers");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.OnboardingCase", b =>
                {
                    b.Property<Guid>("OnboardingCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MembershipAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OnboardingCaseId");

                    b.HasIndex("MembershipAgreementId")
                        .IsUnique();

                    b.HasIndex("OrganizerId");

                    b.ToTable("OnboardingCases");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RegisteredByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RegisteredByAdminId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.OTPToken", b =>
                {
                    b.Property<Guid>("OTPTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OTPTokenId");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("OTPTokens");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationChecklistSubmission", b =>
                {
                    b.Property<Guid>("VerificationChecklistSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompositeScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("OverallComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VerificationScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VerificationChecklistSubmissionId");

                    b.HasIndex("VerificationScheduleId");

                    b.ToTable("VerificationChecklistSubmissions");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationCriterion", b =>
                {
                    b.Property<Guid>("VerificationCriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("VerificationRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("VerificationCriterionId");

                    b.HasIndex("VerificationRoundId");

                    b.ToTable("VerificationCriteria");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationCriterionRating", b =>
                {
                    b.Property<Guid>("VerificationCriterionRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("VerificationChecklistSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VerificationCriterionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VerificationCriterionRatingId");

                    b.HasIndex("VerificationCriterionId");

                    b.HasIndex("VerificationChecklistSubmissionId", "VerificationCriterionId")
                        .IsUnique();

                    b.ToTable("VerificationCriterionRatings", t =>
                        {
                            t.HasCheckConstraint("CK_VerificationCriterionRating_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationRound", b =>
                {
                    b.Property<Guid>("VerificationRoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VerificationRoundId");

                    b.HasIndex("CircleId");

                    b.ToTable("VerificationRounds");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationSchedule", b =>
                {
                    b.Property<Guid>("VerificationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("LocationLink")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<Guid>("VerificationRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoLink")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("VerificationScheduleId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("VerificationRoundId");

                    b.ToTable("VerificationSchedules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Agreement___Payment.MembershipAgreement", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Marketplace___Applications.MembershipApplication", "MembershipApplication")
                        .WithOne("MembershipAgreement")
                        .HasForeignKey("MonyLoop.Domain.Entities.Agreement___Payment.MembershipAgreement", "MembershipApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipApplication");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Agreement___Payment.PaymentTransaction", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", "Circle")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.MemberLedger", "MemberLedger")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("MemberLedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("MemberLedger");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.AuditLog", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.CircleRequest", "CircleRequest")
                        .WithOne()
                        .HasForeignKey("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CircleRequest");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.CircleRequest", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByOrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", "ExistingCircle")
                        .WithMany("ReplacementRequests")
                        .HasForeignKey("ExistingCircleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExistingCircle");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.CircleSlot", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", "Circle")
                        .WithMany("CircleSlots")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.MemberLedger", "MemberLedger")
                        .WithOne("CircleSlot")
                        .HasForeignKey("MonyLoop.Domain.Entities.CircleRequestManagement.CircleSlot", "MemberLedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Circle");

                    b.Navigation("MemberLedger");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.MarketplaceListing", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", "Circle")
                        .WithOne("MarketplaceListing")
                        .HasForeignKey("MonyLoop.Domain.Entities.CircleRequestManagement.MarketplaceListing", "CircleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Marketplace___Applications.MembershipApplication", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.MarketplaceListing", "MarketplaceListing")
                        .WithMany("MembershipApplications")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarketplaceListing");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.Document", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.DocumentRequirement", "DocumentRequirement")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentRequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.OnboardingCase", "OnboardingCase")
                        .WithMany("Documents")
                        .HasForeignKey("OnboardingCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentRequirement");

                    b.Navigation("OnboardingCase");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.MemberLedger", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "ActivatedByAdmin")
                        .WithMany()
                        .HasForeignKey("ActivatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.OnboardingCase", "OnboardingCase")
                        .WithOne("MemberLedger")
                        .HasForeignKey("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.MemberLedger", "OnboardingCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivatedByAdmin");

                    b.Navigation("OnboardingCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.OnboardingCase", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Agreement___Payment.MembershipAgreement", "MembershipAgreement")
                        .WithOne("OnboardingCase")
                        .HasForeignKey("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.OnboardingCase", "MembershipAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipAgreement");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "RegisteredByAdmin")
                        .WithMany()
                        .HasForeignKey("RegisteredByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RegisteredByAdmin");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.OTPToken", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "User")
                        .WithMany("OTPTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.RefreshToken", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationChecklistSubmission", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Verification.VerificationSchedule", "VerificationSchedule")
                        .WithMany("VerificationChecklistSubmissions")
                        .HasForeignKey("VerificationScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VerificationSchedule");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationCriterion", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Verification.VerificationRound", "VerificationRound")
                        .WithMany("VerificationCriteria")
                        .HasForeignKey("VerificationRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationRound");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationCriterionRating", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Verification.VerificationChecklistSubmission", "VerificationChecklistSubmission")
                        .WithMany("VerificationCriterionRatings")
                        .HasForeignKey("VerificationChecklistSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.Verification.VerificationCriterion", "VerificationCriterion")
                        .WithMany("VerificationCriterionRatings")
                        .HasForeignKey("VerificationCriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VerificationChecklistSubmission");

                    b.Navigation("VerificationCriterion");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationRound", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", "Circle")
                        .WithMany("VerificationRounds")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationSchedule", b =>
                {
                    b.HasOne("MonyLoop.Domain.Entities.Marketplace___Applications.MembershipApplication", "MembershipApplication")
                        .WithMany("VerificationSchedules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonyLoop.Domain.Entities.Verification.VerificationRound", "VerificationRound")
                        .WithMany("VerificationSchedules")
                        .HasForeignKey("VerificationRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipApplication");

                    b.Navigation("VerificationRound");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Agreement___Payment.MembershipAgreement", b =>
                {
                    b.Navigation("OnboardingCase");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.Circle", b =>
                {
                    b.Navigation("CircleSlots");

                    b.Navigation("MarketplaceListing");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("ReplacementRequests");

                    b.Navigation("VerificationRounds");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.CircleRequestManagement.MarketplaceListing", b =>
                {
                    b.Navigation("MembershipApplications");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Marketplace___Applications.MembershipApplication", b =>
                {
                    b.Navigation("MembershipAgreement");

                    b.Navigation("VerificationSchedules");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.DocumentRequirement", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.MemberLedger", b =>
                {
                    b.Navigation("CircleSlot");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Onboarding___Member_Ledger.OnboardingCase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("MemberLedger");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.UserAuth.ApplicationUser", b =>
                {
                    b.Navigation("OTPTokens");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationChecklistSubmission", b =>
                {
                    b.Navigation("VerificationCriterionRatings");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationCriterion", b =>
                {
                    b.Navigation("VerificationCriterionRatings");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationRound", b =>
                {
                    b.Navigation("VerificationCriteria");

                    b.Navigation("VerificationSchedules");
                });

            modelBuilder.Entity("MonyLoop.Domain.Entities.Verification.VerificationSchedule", b =>
                {
                    b.Navigation("VerificationChecklistSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
