using MonyLoop.Application.DTOs.AgreementPayment.PaymentTransaction;
using MonyLoop.Application.ServicesAbstractions.AgreementPayment;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MonyLoop.Infrastructure
{
    public class PaymentReceiptPdfService : IPaymentReceiptPdfService
    {
        public byte[] GenerateReceiptPdf(PaymentReceiptResponse receipt)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);

                    page.Margin(40);

                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .AlignCenter()
                        .Text("AMAN MONEY LOOP")
                        .Bold()
                        .FontSize(22);

                    page.Content()
                        .PaddingVertical(20)
                        .Column(column =>
                        {
                            column.Spacing(12);

                            column.Item()
                                .AlignCenter()
                                .Text("Payment Receipt")
                                .Bold()
                                .FontSize(18);

                            column.Item()
                                .Text($"Receipt Number: {receipt.ReceiptNumber}");

                            column.Item()
                                .Text($"Transaction ID: {receipt.PaymentTransactionId}");
                            column.Item()
                                .Text($"Transaction Type: {receipt.TransactionType}");

                            column.Item()
                                .Text($"Transaction Status: {receipt.TransactionStatus}");

                            column.Item()
                                .Text($"Member Ledger ID: {receipt.MemberLedgerId}");

                            column.Item()
                                .Text($"Circle ID: {receipt.CircleId}");

                            column.Item()
                                .Text($"Amount: {receipt.Amount:F2}");

                            column.Item()
                                .Text($"Payment Method: {receipt.PaymentMethod}");

                            column.Item()
                                .Text(
                                    $"Transaction Reference: " +
                                    $"{receipt.TransactionReference ?? "N/A"}");

                            column.Item()
                                .Text(
                                    $"Transaction Date: " +
                                    $"{receipt.TransactionDate:yyyy-MM-dd HH:mm:ss} UTC");
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Aman Money Loop");
                });
            });

            return document.GeneratePdf();
        }
    }
}